import type { Metadata } from 'next';
import './globals.css';
import Sidenav from '@/components/Navbar';
import { inter } from '@/fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased text-black`}>
        <Sidenav />
        <div className='ml-20 bg-white min-h-screen'>
          {children}
        </div>
      </body>
    </html>
  );
}
